package org.synyx.urlaubsverwaltung.person;

/**
 * Describes which kind of mail notifications a person can have.
 */
public enum MailNotification {

    NOTIFICATION_EMAIL_APPLICATION_MANAGEMENT_ALL,
    NOTIFICATION_EMAIL_APPLICATION_MANAGEMENT_DEPARTMENT,
    NOTIFICATION_EMAIL_APPLICATION_APPLIED,
    NOTIFICATION_EMAIL_APPLICATION_ALLOWED,
    NOTIFICATION_EMAIL_APPLICATION_REVOKED,
    NOTIFICATION_EMAIL_APPLICATION_REJECTED,
    NOTIFICATION_EMAIL_APPLICATION_TEMPORARY_ALLOWED,
    NOTIFICATION_EMAIL_APPLICATION_CANCELLATION,
    NOTIFICATION_EMAIL_APPLICATION_EDITED,
    NOTIFICATION_EMAIL_APPLICATION_CONVERTED,
    NOTIFICATION_EMAIL_APPLICATION_UPCOMING,

    NOTIFICATION_EMAIL_APPLICATION_HOLIDAY_REPLACEMENT,
    NOTIFICATION_EMAIL_APPLICATION_HOLIDAY_REPLACEMENT_UPCOMING,

    NOTIFICATION_EMAIL_PERSON_NEW_MANAGEMENT_ALL,

    NOTIFICATION_EMAIL_OVERTIME_MANAGEMENT_ALL,

    NOTIFICATION_EMAIL_SICKNOTE_END_OF_SICK_PAY,
    NOTIFICATION_EMAIL_SICKNOTE_END_OF_SICK_PAY_MANAGEMENT_ALL,
}
