---
apiVersion: v2
name: urlaubsverwaltung
description: Helm Chart for the urlaubsverwaltung
type: application
version: "7.2.0"
appVersion: 6.2.0
keywords:
  - urlaub
home: https://github.com/urlaubsverwaltung/urlaubsverwaltung
sources:
  - https://github.com/urlaubsverwaltung/urlaubsverwaltung
maintainers:
  - name: Johannes Graf
    email: Johannes.Graf@focus-shift.de
  - name: Tobias Schneider
    email: Tobias.Schneider@focus-shift.de
