package org.synyx.urlaubsverwaltung.person.web;

/**
 * Describes which kind of mail notifications a person can have.
 */
public enum PersonMailNotificationDto {

    NOTIFICATION_EMAIL_APPLICATION_MANAGEMENT_ALL,
    NOTIFICATION_EMAIL_APPLICATION_MANAGEMENT_DEPARTMENT,
    NOTIFICATION_EMAIL_APPLICATION,
    NOTIFICATION_EMAIL_APPLICATION_UPCOMING,

    NOTIFICATION_EMAIL_APPLICATION_HOLIDAY_REPLACEMENT,
    NOTIFICATION_EMAIL_APPLICATION_HOLIDAY_REPLACEMENT_UPCOMING,

    NOTIFICATION_EMAIL_PERSON_NEW_MANAGEMENT_ALL,

    NOTIFICATION_EMAIL_OVERTIME_MANAGEMENT_ALL,
}
