#!/usr/bin/env bash

ESC_SEQ="\x1b["
COL_RESET=$ESC_SEQ"39;49;00m"
COL_MAGENTA=$ESC_SEQ"35;01m"

packageJsonUpdated=$(git diff-tree -r --name-only --no-commit-id ORIG_HEAD HEAD | grep package.json)

if [ "$packageJsonUpdated" ]; then

    printf "%b" "$COL_MAGENTA"
    printf "package.json has been touched\n"
    printf "Please wait a moment. I will update frontend modules for you 😽\n"
    printf "%b" "$COL_RESET"

    ./mvnw frontend:install-node-and-npm frontend:npm@npm-install
fi
