package org.synyx.urlaubsverwaltung.extension.backup.model;

import org.synyx.urlaubsverwaltung.workingtime.FederalState;

public enum FederalStateDTO {
    NONE,

    GERMANY_BADEN_WUERTTEMBERG,
    GERMANY_BAYERN,
    GERMANY_BAYERN_MUENCHEN,
    GERMANY_BAYERN_AUGSBURG,
    GERMANY_BAYERN_WUERZBURG,
    GERMANY_BAYERN_REGENSBURG,
    GERMANY_BAYERN_INGOLSTADT,
    GERMANY_BERLIN,
    GERMANY_BRANDENBURG,
    GERMANY_BREMEN,
    GERMANY_HAMBURG,
    GERMANY_HESSEN,
    GERMANY_MECKLENBURG_VORPOMMERN,
    GERMANY_NIEDERSACHSEN,
    GERMANY_NORDRHEIN_WESTFALEN,
    GERMANY_RHEINLAND_PFALZ,
    GERMANY_SAARLAND,
    GERMANY_SACHSEN,
    GERMANY_SACHSEN_ANHALT,
    GERMANY_SCHLESWIG_HOLSTEIN,
    GERMANY_THUERINGEN,

    GREECE_GREECE,

    AUSTRIA_BURGENLAND,
    AUSTRIA_KAERNTEN,
    AUSTRIA_NIEDEROESTERREICH,
    AUSTRIA_OBEROESTERREICH,
    AUSTRIA_SALZBURG,
    AUSTRIA_STEIERMARK,
    AUSTRIA_TIROL,
    AUSTRIA_VORARLBERG,
    AUSTRIA_WIEN,

    SWITZERLAND_AARGAU,
    SWITZERLAND_APPENZELL_INNERRHODEN,
    SWITZERLAND_APPENZELL_AUSSERRHODEN,
    SWITZERLAND_BERN,
    SWITZERLAND_BASEL_LANDSCHAFT,
    SWITZERLAND_BASEL_STADT,
    SWITZERLAND_FREIBURG,
    SWITZERLAND_GENF,
    SWITZERLAND_GLARUS,
    SWITZERLAND_GRAUBUENDEN,
    SWITZERLAND_JURA,
    SWITZERLAND_LUZERN,
    SWITZERLAND_NEUENBURG,
    SWITZERLAND_NIDWALDEN,
    SWITZERLAND_OBWALDEN,
    SWITZERLAND_ST_GALLEN,
    SWITZERLAND_SCHAFFHAUSEN,
    SWITZERLAND_SOLOTHURN,
    SWITZERLAND_SCHWYZ,
    SWITZERLAND_THURGAU,
    SWITZERLAND_TESSIN,
    SWITZERLAND_URI,
    SWITZERLAND_WAADT,
    SWITZERLAND_WALLIS,
    SWITZERLAND_ZUG,
    SWITZERLAND_ZUERICH,

    UNITED_KINGDOM_ALDERNEY,
    UNITED_KINGDOM_ENGLAND,
    UNITED_KINGDOM_GUERNSEY,
    UNITED_KINGDOM_ISLE_OF_MAN,
    UNITED_KINGDOM_JERSEY,
    UNITED_KINGDOM_NORTHERN_IRELAND,
    UNITED_KINGDOM_SCOTLAND,
    UNITED_KINGDOM_WALES,

    MALTA,

    ITALY,

    CROATIA,

    SPAIN_ANDALUCIA,
    SPAIN_ARAGON,
    SPAIN_CEUTA,
    SPAIN_MELILLA,
    SPAIN_CASTILE_AND_LEON,
    SPAIN_CASTILE_LA_MANCHA,
    SPAIN_CANARY_ISLANDS,
    SPAIN_CATALONIA,
    SPAIN_BARCELONA,
    SPAIN_EXTREMADURA,
    SPAIN_GALICIA,
    SPAIN_BALEARIC_ISLAND,
    SPAIN_LA_RIOJA,
    SPAIN_MADRID,
    SPAIN_MURCIA,
    SPAIN_NAVARRA,
    SPAIN_ASTURIAS,
    SPAIN_EUSKADI,
    SPAIN_CANTABRIA,
    SPAIN_VALENCIA,

    NETHERLANDS,

    LITHUANIA,

    BELGIUM,

    POLAND,

    USA_MARYLAND,
    USA_VIRGINIA,
    USA_WASHINGTON_DC;

    public FederalState toFederalState() {
        return FederalState.valueOf(this.name());
    }
}
