name: Mutation Testing

on:
  schedule:
    - cron: "1 3 * * FRI"

jobs:
  build:
    name: PiTesT
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Cache npm dependencies
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Cache pom dependencies
        uses: actions/cache@v2
        with:
          path: |
            ~/.m2/repository
            node/
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Mutation Testing
        run: ./mvnw --batch-mode clean test org.pitest:pitest-maven:mutationCoverage
      - uses: actions/upload-artifact@v2
        with:
          name: pi-report
          path: target/pit-reports/
